version: '3.8'

services:
  nginx:
    build: .
    container_name: nginx_server
    ports:
      - "92:80"
      - "422:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro
      - ./logs:/var/log/nginx
      - ./nginx/ssl:/etc/nginx/ssl:ro
