version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: airlock_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/app  # Monte le dossier courant dans /app
      - ./nginx.conf:/etc/nginx/nginx.conf  # Monte le fichier de config Nginx
    restart: always