version: '3.8'

services:
  php:
    build: .
    container_name: php-container
    volumes:
      - ./code:/var/www/html:cached
      - ./logs/php:/var/log/php:cached
    networks:
      - app_network
    ports:
      - "9000:9000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: airlockunlock
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
    ports:
      - "3347:3306"  # <-- MODIFIÉ
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql-container
      PMA_USER: root
      PMA_PORT: 3306
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - app_network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-ssl
    depends_on:
      - php
    volumes:
      - ./code:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/certs:ro
      - ./logs/nginx:/var/log/nginx:cached
    ports:
      - "91:80"     # <-- MODIFIÉ
      - "421:443"   # <-- MODIFIÉ
    networks:
      - app_network

volumes:
  dbdata:
    driver: local

networks:
  app_network:
    driver: bridge
