version: '3.8'

services:
  # Frontend Nginx (site statique)
  web-nginx:
    build: ./Web
    container_name: web_nginx
    ports:
      - "92:80"
      - "422:443"
    volumes:
      - ./Web/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./Web/html:/usr/share/nginx/html:ro
      - ./Web/logs:/var/log/nginx
      - ./Web/nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - app_network

  # Backend PHP (API)
  php:
    build: ./APIs
    container_name: php_container
    environment:
      - JWT_SECRET_KEY=votre_cle_secrete_sure
    volumes:
      - ./APIs/code:/var/www/html:cached 
      - ./APIs/logs/php:/var/log/php:cached
      - vendor:/var/www/html/vendor
    networks:
      - app_network
    ports:
      - "9000:9000"
    depends_on:
      - mysql

  # Base de données MySQL
  mysql:
    image: mysql:8
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: airlockunlock
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3347:3306"
    networks:
      - app_network

  # Interface PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql_container
      PMA_USER: root
      PMA_PORT: 3306
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - app_network

  # Backend Nginx (PHP-FPM)
  api-nginx:
    image: nginx:stable-alpine
    container_name: api_nginx
    depends_on:
      - php
    volumes:
      - ./APIs/code:/var/www/html:ro
      - ./APIs/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./APIs/ssl:/etc/nginx/certs:ro
      - ./APIs/logs/nginx:/var/log/nginx:cached
    ports:
      - "91:80"
      - "421:443"
    networks:
      - app_network

volumes:
  dbdata:
  vendor:

networks:
  app_network:
    driver: bridge
