services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    # restart: always
    ports:
      - "92:92"
      - "422:422"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html
      - ./img:/usr/share/nginx/html/img  # Ajout du dossier des images
      - ./logs:/var/log/nginx
      - ./nginx/ssl:/etc/nginx/ssl
#     networks:
#       - webnet

# networks:
#   webnet: