FROM php:8.3-fpm

# Installer les prérequis nécessaires à composer et extensions PHP
RUN apt-get update && apt-get install -y unzip git zip libzip-dev \
    && docker-php-ext-install pdo pdo_mysql mysqli \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Installer Composer (si besoin)
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

# Copier les fichiers composer.json et composer.lock d'abord (pour optimiser le cache Docker)
COPY code/composer.json code/composer.lock ./


# Installer les dépendances composer dans le dossier vendor/
RUN composer install --no-dev --optimize-autoloader

# Copier le reste du code de l'application
COPY . .

# Permissions, dossier photos etc. si besoin
RUN mkdir -p AirlockUnlock/bien/photos && chown -R www-data:www-data AirlockUnlock/bien/photos && chmod -R 755 AirlockUnlock/bien/photos

EXPOSE 9000
CMD ["php-fpm"]
